#!/bin/sh

set -e

# Add any commands used in the config here. Required modules will
# be added automatically.
commands="serial play videotest gfxmode background_image videoinfo probe regexp smbios sleep extract_entries_source"

# Modules that aren't directly required by a command. Dependencies will
# be resolved automatically.
mods="all_video png jpeg videotest gfxterm"

add_grub_command() {
        local platform="$1"
        local cmd="$2"

        for mod in $(grep "^\*\?${cmd}: " ${BUILDROOT}/usr/lib/grub/${platform}/command.lst | sed -e "s%^\*\?${cmd}: %%g")
        do
                echo "Command ${cmd} in ${platform} depends on ${mod}"
                add_grub_module ${platform} ${mod}
        done
}

add_grub_module() {
        local platform="$1"
        local mod="$2"

        mkdir -p ${BUILDROOT}/boot/grub/${platform}

        if [ -e "${BUILDROOT}/boot/grub/${platform}/${mod}.mod" ]
        then
                return
        fi

        for dep in $(readelf -p .moddeps ${BUILDROOT}/usr/lib/grub/${platform}/${mod}.mod 2> /dev/null| grep ']' | cut -f2 -d])
        do
                echo "Module ${mod} in ${platform} depends on ${dep}"
                add_grub_module ${platform} ${dep}
        done
        cp ${BUILDROOT}/usr/lib/grub/${platform}/${mod}.mod ${BUILDROOT}/boot/grub/${platform}/
}

for platform in i386-pc x86_64-efi
do
        for cmd in ${commands}
        do
                add_grub_command "${platform}" "${cmd}"
        done

        for mod in ${mods}
        do
                add_grub_module "${platform}" "${mod}"
        done

        cp ${BUILDROOT}/usr/lib/grub/${platform}/command.lst ${BUILDROOT}/boot/grub/${platform}/
done

mkdir -p ${BUILDROOT}/boot/grub/fonts
cp ${BUILDROOT}/usr/share/grub/unicode.pf2 ${BUILDROOT}/boot/grub/fonts
cp -r -t "${BUILDROOT}" "${BUILDROOT}/usr/share/mangos/boot"
