#!/bin/sh

if [ -z "${KERNEL_CMDLINE}" ]
then
    KERNEL_CMDLINE="$(cat /proc/cmdline)"
fi

while [ $# -gt 0 ]
do
    case "$1" in
        -h|--help)
            echo 'usage: mangos-install [BLOCK_DEVICE|ask]'
            echo
            echo 'Downloads and installs MANGOS onto BLOCK_DEVICE.'
            echo
            echo 'If called without arguments or with a single argument "ask",'
            echo 'a dialog will be presented with a list of detected block devices.'
            exit 0
            ;;
        -s)
            DOWNLOAD_URL="$2"
            shift 2
            ;;
        -n|--dry-run)
            echo="/bin/echo --"
            shift
            ;;
        *)
            install_target=$1
            shift
            ;;
    esac
done

if [ -z "${install_target}" ]
then
    target="$(sed -e 's%.*mangos_install_target=\([a-z0-9/:.-]\+\).*%\1%' /proc/cmdline)"
    if [ -n "${target}" ]
    then
        install_target="${target}"
    fi
fi

install_target="${install_target:-ask}"

if [ "${install_target}" = "ask" ]
then
        if ! lsblk -p -o TYPE,NAME,VENDOR,MODEL,SERIAL -l | grep ^disk | cut -f2- -d' ' | sed -e 's/ \+/ /g' | while read bdev info; do /bin/echo -e "$bdev\0$info\0" ; done | tr -d '\n' | xargs -0 whiptail --menu "Install target" 15 50 0 2> /tmp/mangos_install_target
        then
                echo "Install cancelled"
                exit 1
        fi
        install_target="$(cat /tmp/mangos_install_target ; rm /tmp/mangos_install_target)"
fi

if [ -z "${DOWNLOAD_URL}" ]
then
    . /etc/os-release

    DOWNLOAD_URL="${MANGOS_GITHUB_URL}/releases/download/v${IMAGE_VERSION}/mangos_${IMAGE_VERSION}.raw.zst"
fi

